### PR TITLE
Change to PEP 517 style python package building from `python setup.py install`

### LINKED ISSUE #1593: Windows portable doesn't start anymore since maybe one month ago
Hi, I'm under the impression that the portable windows version doesn't open anymore since maybe a month. I'm using 3.11.4.1093 right now, which still opens on my system. Today I thought I'd give it a try again with 1135, but still no luck. No log is created. Any idea or workaround?
Thanks.

### LINKED ISSUE #1656: `python setup.py` and the use of `setup.py` as a command line tool are deprecated
Hello I am not sure where to post this I'm sorry if this is not the place for it.
# Deprecation
According to [this guide](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/) from the Python packaging authority, the role of `setup.py` is reduced to just a configuration file for setuptools as a [build backend](https://packaging.python.org/en/latest/glossary/#term-Build-Backend).
It is my understanding that `gpodder` is not a pure python package and needs to have files outside of `site-packages` directory, like the localization files and GTK UI files in `.../share/gpodder/ui/*.ui`. This is currently done with a makefile that linux distribution packagers run to make a complete package. This makefile runs commands like `$(PYTHON) setup.py install --root=$(DESTDIR) --prefix=$(PREFIX) --optimize=1` for `make install` as mentioned in the linked guide, `setup.py install` is deprecated.

support for `pyproject.toml` is added to [setuptools from version 61.0](https://setuptools.pypa.io/en/stable/userguide/pyproject_config.html). And considering that debian stable ships [setuptools 66.1.1-1](https://packages.debian.org/stable/python/python3-setuptools), I think we can safely assume that there will be no problem with the migration to `pyproject.toml`.

# What needs to be done and why:
[setuptools documentation](https://setuptools.pypa.io/en/stable/userguide/quickstart.html) says 
> Every python package must provide a `pyproject.toml` and specify the backend (build system) it wants to use.

So I think we should convert from `setup.py` to a `pyproject.toml` file.
I have done some of the work in [this branch](https://github.com/masoudd/gpodder/tree/update_package_build_flow).
Although I'm not sure we really need to delete `setup.py` as [said here](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#should-setup-py-be-deleted):
>There is likely no modification needed in setup.py

Also not sure where the metadata about the project should be: in `src/gpodder/__init__.py`? or in `pyproject.toml`?

Also the makefile needs to be changed to use a [build frontend](https://packaging.python.org/en/latest/glossary/#term-Build-Frontend) to make a wheel and install the wheel then do what the `python setup.py install` command does, which is finding the extra files and copying them to the right place according to values set in these environment vars: `LINGUAS`, `GPODDER_MANPATH_NO_SHARE` and `GPODDER_INSTALL_UIS`. And `--root` and `--prefix` flags that make provides.

List of make rules in `makefile` that need to changed:
- `release`
- `install`
- `install-win`
- `share/man/man1/gpodder.1`
- `share/man/man1/gpo.1`
- `clean`

I am not sure about where we should add the user runnable commands (apparently called "entry points") in the `/bin` directory of the system. I think the makefile should do it, but there is something about it in [PyPA docs]](https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts) and [setuptools docs](https://setuptools.pypa.io/en/stable/userguide/entry_point.html)

And ultimately a rework of windows build process as it is not working right and is blocking a new release (#1593)
# References
- [pyproject.toml specification](https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec) (originally PEP 621)
- [PEP 518](https://peps.python.org/pep-0518/)
- [https://packaging.python.org/en/latest/guides/writing-pyproject-toml/](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/)
- [https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

### PR DESCRIPTION
**Pull request by masoudd**
I marked this as a draft to ask for your opinion. Please let me know if anything needs to change.
- created `pyproject.toml` and moved to `python -m build`
- slightly modified `_base.sh` to get windows build working
- tested in my local msys install and windows build is working. Need to confirm if it works on Appveyor as well (✔)

What needs to happen:
- [x] Find a substitute for `python setup.py clean` in `makefile`
- [ ] solve `tools/win_installer/misc/depcheck.py` failing when called in `_base.sh` (currently commented out, which adds around 18 MB to the extracted portable folder size)

Also the new socks networking option needs [pysocks](https://pypi.org/project/PySocks/) as optional dep which needs to be added to distro packages of gpodder. I can make it happen in archlinux but other distros need to be contacted.

Fixes #1656, fixes #1593

### CODE REVIEW

**Comment by auouymous** [comment]
Have you tested this on Windows? #1637 was an attempt to fix it by updating to a new version of the build script, but I also had to disable depcheck.

I will review this in two days when I get back.

**Comment by masoudd** [comment]
> Have you tested this on Windows?

Yes. I have an up to date windows 10 system. Installed msys and updated it, and tested on there. The built portable exe and installer both result in a gpodder that has the missing `share/gpodder/gtk/*.ui` that was causing #1593. Also the `yt_dlp` that is included in it is version `2024.8.6` which may help with #1634.

> #1637 was an attempt to fix it by updating to a new version of the build script, but I also had to disable depcheck.

I have not tested that pull request. I will run it on my system and report back there. And appveyor artifacts of it are deleted now. If you could make it re run the build on appveyor I will also test them.
Ideally I can rebase this on that branch if it is pulled first.

**Comment by auouymous** [comment]
Sorry for the delay, I will eventually get to this PR when I feel better.

#1637 was nothing more than updating that script to changes made upstream at https://github.com/quodlibet/quodlibet/tree/main/dev-utils/win_installer, which did not work. I will clean it up and merge some of its changes after this PR is merged.

**Comment by auouymous** [comment]
The appveyor build is missing most `*.py` files in gpodder, it only has the the `*.pyc` files.

You commented out two lines in `_base.sh` they should be removed if no longer needed. The depcheck line can remain commented, but maybe add a comment to fix or remove it.

When ready, do you want me to squash the commits or did you want to refactor them?

**Comment by auouymous** [comment]
The makefile uses build and pip, are they both required or can build also be used to install?

**Comment by masoudd** [comment]
Hello. Thank you for taking the time to review this. I hope you have recovered fully.

> The appveyor build is missing most `*.py` files in gpodder, it only has the the `*.pyc` files.

Yes. This was intended behavior in `_base.sh` (I think to reduce the final size). It calls [`python -m compileall -b`](https://docs.python.org/3/library/compileall.html) on the root dir of the whole temporary msys install and then deletes all `*.py` files.

I merely moved it from `cleanup_before()` to `cleanup_after()` because `site-packages/pip/__pip-runner__.py` was needed after calling `cleanup_before()`. And also added an exception for the gpodder extentions directory because [extensions.py](https://github.com/gpodder/gpodder/blob/0f55098e1eea1eafa15417cc17acb4d3a068a607/src/gpodder/extensions.py#L378) looks for `*.py` only, and would not recognize the extensions otherwise.

> You commented out two lines in `_base.sh` they should be removed if no longer needed. The depcheck line can remain commented, but maybe add a comment to fix or remove it.

Done.

> When ready, do you want me to squash the commits or did you want to refactor them?

Yes. squash if needed. Ignoring depcheck.py, this pr is ready IMO as `setup.py clean` is not critically needed.

> The makefile uses build and pip, are they both required or can build also be used to install?
Honestly I'm not sure. Looking through [build docs](https://build.pypa.io/en/stable/index.html) it seems `build` defaults to to `pip` as the installer. Maybe we can get rid of `build` and use `pip` as the build frontend too. [As said here](https://packaging.python.org/en/latest/glossary/#term-Build-Frontend) pip is considered a build frontend too. I will look into it more.

**Comment by auouymous** [comment]
> I merely moved it from `cleanup_before()` to `cleanup_after()` because `site-packages/pip/__pip-runner__.py` was needed after calling `cleanup_before()`. And also added an exception for the gpodder extentions directory because [extensions.py](https://github.com/gpodder/gpodder/blob/0f55098e1eea1eafa15417cc17acb4d3a068a607/src/gpodder/extensions.py#L378) looks for `*.py` only, and would not recognize the extensions otherwise.

All of gpodder's `.py` files (excluding dependencies) need to be there so users can modify them. Can pip runner be saved and restored after pruning in `cleanup_before()`? Maybe add an extension to it, prune, then remove extension?


> Maybe we can get rid of build and use pip as the build frontend too. [As said here](https://packaging.python.org/en/latest/glossary/#term-Build-Frontend) pip is considered a build frontend too. I will look into it more.

Thank you. Not requiring users to have both would be nice.

**Comment by auouymous** [comment]
Are you able to reproduce the issues in https://github.com/gpodder/gpodder/issues/1654#issuecomment-2338719406 in the appveyor build? I doubt the `.py` files are needed to find a global variable or edit settings.

**Comment by masoudd** [comment]
>All of gpodder's .py files (excluding dependencies) need to be there so users can modify them. Can pip runner be saved and restored after pruning in cleanup_before()? Maybe add an extension to it, prune, then remove extension?

Hmm yes I can keep all the gpodder `.py` files in the final artifact. I feel like singling out one file for pip runner would be fragile as it might need other files in the future.

>Thank you. Not requiring users to have both would be nice.

I think the different users and what they need to have installed needs to be clarified:
1) Making a "[source distribution](https://packaging.python.org/en/latest/discussions/package-formats/#what-is-a-source-distribution)" package:
Which is made using makefile rule `release:` which runs `python setup.py sdist`.
`pip` [does not do that](https://pip.pypa.io/en/stable/topics/workflow/#pip-is-not-a-workflow-management-tool). We need something like `build` for that and I think that's OK because only the maintainer of the project needs to run that once for each release.

2) Linux distro packagers that take that source distribution and make a wheel from it and package it for their distro.
    - They don't strictly need `build`. `pip` can make a wheel and install it in the appropriate place for them to essentially zip it up and call it a distro package. It is important to not change what they need to do here with this pull request if possible. It would be a lot of work to update the packaging process of each distro one by one. That's why I went with pip in the pull request initially.

    - For example I'll use archlinux because that's the distro I'm most familiar with the packaging process: [Here](https://gitlab.archlinux.org/archlinux/packaging/packages/gpodder/-/blob/main/PKGBUILD?ref_type=heads) is how they do it. They just download this:
`https://github.com/gpodder/$pkgname/archive/$pkgver/$pkgname-$pkgver.tar.gz`
extract it and run `make messages` and then `make install`. The only thing that is changed is `python setup.py install` to `pip install .` from the `make install` rule.

    - After asking in debian and archlinux irc channels, it seems like using pip here is a bad idea. Nothing should be downloaded and installed here. I'm now considering `build` to build the wheel and [`installer`](https://installer.pypa.io/en/stable/cli/installer/) to install it. This means installer and build should be added to `requires` array in the `[build-system]` table in `pyproject.toml`. (Also pip is not available by default in archlinux build env).

3) The end users that run gpodder. No new dependencies here. Hopefully nothing needs to be done here other than just installing the new package.

**Comment by masoudd** [comment]
> Are you able to reproduce the issues in https://github.com/gpodder/gpodder/issues/1654#issuecomment-2338719406 in the appveyor build? I doubt the .py files are needed to find a global variable or edit settings.

I'll look into this. the _proxies is something I introduced in the last pull request. I'm not sure currently how that is happening

**Comment by auouymous** [comment]
> > Are you able to reproduce the issues in [#1654 (comment)](https://github.com/gpodder/gpodder/issues/1654#issuecomment-2338719406) in the appveyor build? I doubt the .py files are needed to find a global variable or edit settings.
> 
> I'll look into this. the _proxies is something I introduced in the last pull request. I'm not sure currently how that is happening

I think that was two installed versions of gpodder.

**Comment by masoudd** [comment]
Tested the successful build of the portable from appveyor. It works! 🎉
But it is using the settings in `Documents\gPodder\Settings.json`. Is that intended? Or should it make a new one in the `data` dir in the portable dir? If yes, I'll make a new issue and investigate it in a new pull request.

Also ticking `[ ] Find a substitute for python setup.py clean in makefile` for now. The `clean` make rule seems to clean everything correctly.

**Comment by auouymous** [comment]
> it is using the settings in `Documents\gPodder\Settings.json`. Is that intended? Or should it make a new one in the `data` dir in the portable dir?

I don't know what the portable build even is, does the 3.11.4 release do it?

I'll try to review the new changes soon.

**Comment by masoudd** [comment]
> > it is using the settings in `Documents\gPodder\Settings.json`. Is that intended? Or should it make a new one in the `data` dir in the portable dir?
> 
> I don't know what the portable build even is, does the 3.11.4 release do it?

No, it correctly uses the `config` dir in the portable dir. So this wrong behavior is introduced in this build.

Sorry `data` was wrong. `config` is where the portable keeps it's own settings and downloads.
Basically the portable exe extracts this:
```
$ tree gpodder-3.11.4-portable/ -L 2
gpodder-3.11.4-portable/
├── config
│   ├── Database
│   ├── gpodder.net
│   ├── Logs
│   └── Settings.json
├── data
│   ├── bin
│   ├── contents.txt
│   ├── etc
│   ├── lib
│   ├── share
│   └── ssl
├── gpo.lnk
├── gpodder.lnk
└── README.txt
```
the `config/` is empty at first. running the `gpodder.lnk` populates it at first run.
But the portable from commit `38bcc33` still has an empty `config/` and uses the settings of installed gpodder instead.

File: tools/win_installer/_base.sh [hunk 1]
```diff
@@ -108,14 +108,18 @@ function install_deps {
...
+        mingw-w64-"${ARCH}"-python-pip \
         mingw-w64-"${ARCH}"-python-six \
 		mingw-w64-"${ARCH}"-make
 
-    build_pacman -S --noconfirm mingw-w64-"${ARCH}"-python3-setuptools
+    build_pacman -S --noconfirm \
+        mingw-w64-"${ARCH}"-python-setuptools \
+        mingw-w64-"${ARCH}"-python-build \
+        mingw-w64-"${ARCH}"-python-installer
+
```
Comment (auouymous) [inline tools/win_installer/_base.sh:122]: Extra blank line.

File: makefile [hunk 2]
```diff
@@ -96,12 +96,13 @@ $(GPODDER_SERVICE_FILE): $(GPODDER_SERVICE_FILE_IN)
 	intltool-extract --quiet --type=gettext/ini $<
 
 build: messages $(GPODDER_SERVICE_FILE) $(DESKTOP_FILES)
+	$(PYTHON) -m build --wheel --no-isolation
```
Comment (auouymous) [inline makefile:99]: I assume this builds a wheel, could it have its own rule? That would allow the build rule to be called without needing the build dependency, because Gentoo does soemthing else to create a wheel.

``` patch
 build: messages $(GPODDER_SERVICE_FILE) $(DESKTOP_FILES)
+
+buildwheel: build
    $(PYTHON) -m build --wheel --no-isolation
 
-install: build
+install: buildwheel
... 
-install-win: build
+install-win: buildwheel
```

**Review by auouymous — CHANGES_REQUESTED** [review]

**Comment by masoudd** [comment]
I can confirm the portable version now correctly uses the `config` dir in the portable dir for settings and downloads.

**Review by auouymous — APPROVED** [review]

**Comment by auouymous** [comment]
LGTM, are you ready to merge?

> tools/win_installer/misc/depcheck.py failing when called in _base.sh (currently commented out, which adds around 18 MB to the extracted portable folder size)

3.11.4 is 30.7 and 30.6 for installer and portable. Appveyor shows both as 37 for this PR. Is that size increase really caused by depcheck not running, or is because this build includes `/share/icons/AdwaitaLegacy/`?

**Comment by masoudd** [comment]
>LGTM, are you ready to merge?

Yes. I think it is in a good place now. I can also rebase on master if you need.

>3.11.4 is 30.7 and 30.6 for installer and portable. Appveyor shows both as 37 for this PR. Is that size increase really caused by depcheck not running, or is because this build includes /share/icons/AdwaitaLegacy/?

I compared 3.11.4 with cd3db38:

<details><summary>All the difference</summary>
<p>

```
Only in gpodder-cd3db38-portable/data/bin: edit.dll
Only in gpodder-cd3db38-portable/data/bin: gdbus-codegen-script.pyc
Only in gpodder-cd3db38-portable/data/bin: glib-genmarshal-script.pyc
Only in gpodder-cd3db38-portable/data/bin: glib-mkenums-script.pyc
Only in gpodder-cd3db38-portable/data/bin: gtester-report-script.pyc
Only in gpodder-cd3db38-portable/data/bin: libasprintf-0.dll
Only in gpodder-cd3db38-portable/data/bin: libatomic-1.dll
Only in gpodder-cd3db38-portable/data/bin: libbrotlienc.dll
Only in gpodder-cd3db38-portable/data/bin: libcairo-script-interpreter-2.dll
Only in gpodder-cd3db38-portable/data/bin: libcharset-1.dll
Only in gpodder-cd3db38-portable/data/bin: libformw6.dll
Only in gpodder-cd3db38-portable/data/bin: libgailutil-3-0.dll
Only in gpodder-cd3db38-portable/data/bin: libgif-7.dll
Only in gpodder-cd3db38-portable/data/bin: libgirepository-2.0-0.dll
Only in gpodder-cd3db38-portable/data/bin: libgomp-1.dll
Only in gpodder-cd3db38-portable/data/bin: libgthread-2.0-0.dll
Only in gpodder-cd3db38-portable/data/bin: libharfbuzz-subset-0.dll
Only in gpodder-cd3db38-portable/data/bin: libhistory8.dll
Only in gpodder-cd3db38-portable/data/bin: liblzo2-2.dll
Only in gpodder-cd3db38-portable/data/bin: libmenuw6.dll
Only in gpodder-cd3db38-portable/data/bin: libmpdec++-4.dll
Only in gpodder-3.11.4-portable/data/bin: libmpdec-2.dll
Only in gpodder-cd3db38-portable/data/bin: libmpdec-4.dll
Only in gpodder-cd3db38-portable/data/bin: libncurses++w6.dll
Only in gpodder-cd3db38-portable/data/bin: libpcre2-16-0.dll
Only in gpodder-cd3db38-portable/data/bin: libpcre2-32-0.dll
Only in gpodder-cd3db38-portable/data/bin: libpcre2-posix-3.dll
Only in gpodder-cd3db38-portable/data/bin: libpython3.dll
Only in gpodder-cd3db38-portable/data/bin: libquadmath-0.dll
Only in gpodder-cd3db38-portable/data/bin: libreadline8.dll
Only in gpodder-cd3db38-portable/data/bin: libsystre-0.dll
Only in gpodder-cd3db38-portable/data/bin: libtermcap-0.dll
Only in gpodder-cd3db38-portable/data/bin: libtiffxx-6.dll
Only in gpodder-cd3db38-portable/data/bin: libtre-5.dll
Only in gpodder-cd3db38-portable/data/bin: libturbojpeg.dll
Only in gpodder-cd3db38-portable/data/bin: libwebpdecoder-3.dll
Only in gpodder-cd3db38-portable/data/bin: libwebpdemux-2.dll
Only in gpodder-cd3db38-portable/data/bin: libwebpmux-3.dll
Only in gpodder-cd3db38-portable/data/bin: tcl86.dll
Only in gpodder-cd3db38-portable/data/bin: tk86.dll
Only in gpodder-cd3db38-portable/data/lib/girepository-1.0: GioWin32-2.0.typelib
Only in gpodder-cd3db38-portable/data/lib/girepository-1.0: GIRepository-3.0.typelib
Only in gpodder-cd3db38-portable/data/lib/girepository-1.0: GLibWin32-2.0.typelib
Only in gpodder-cd3db38-portable/data/lib/python3.11: __pycache__
Only in gpodder-cd3db38-portable/data/lib/python3.11/collections: __pycache__
Only in gpodder-cd3db38-portable/data/lib/python3.11/encodings: __pycache__
Only in gpodder-3.11.4-portable/data/lib/python3.11/idlelib: NEWS.txt
Only in gpodder-cd3db38-portable/data/lib/python3.11/idlelib: News3.txt
Only in cd3db38-portable/data/lib/python3.11/importlib: __pycache__
Only in gpodder-cd3db38-portable/data/lib/python3.11/lib2to3: Grammar3.11.10.final.0.pickle
Only in gpodder-3.11.4-portable/data/lib/python3.11/lib2to3: Grammar3.11.6.final.0.pickle
Only in gpodder-cd3db38-portable/data/lib/python3.11/lib2to3: PatternGrammar3.11.10.final.0.pickle
Only in gpodder-3.11.4-portable/data/lib/python3.11/lib2to3: PatternGrammar3.11.6.final.0.pickle
Only in gpodder-cd3db38-portable/data/lib/python3.11/re: __pycache__
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/_distutils_hack: __pycache__
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: build
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: build-1.2.2.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: certifi-2023.7.22.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: certifi-2024.6.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/comtypes: clear_cache.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/comtypes: hints.pyi
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/comtypes/tools: codegenerator
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/comtypes/tools: codegenerator.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: comtypes-1.2.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: comtypes-1.4.4.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus: __init__.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus: exceptions.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus: glib.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus/mainloop: __init__.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus/mainloop: glib.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus: mainloop.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/dbus: service.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: distlib-0.3.7.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: distlib-0.3.8.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/gi: events.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/gpodder: __pycache__
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/gpodder_launch: __init__.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/gpodder_launch: gpo.py
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/gpodder_launch: gpodder.py
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: gpodder-3.11.4.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: gpodder-3.11.4-py3.11.egg-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: idna-3.4.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: idna-3.7.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: installer
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: installer-0.7.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: mutagen-1.46.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: mutagen-1.47.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: packaging
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: packaging-24.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_internal/cli: index_command.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_internal/utils: inject_securetransport.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_internal/utils: models.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor/cachecontrol: compat.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/cachecontrol: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/certifi: py.typed
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor: chardet
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor: colorama
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/distro: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/idna: py.typed
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: __about__.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: _elffile.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: _parser.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: _tokenizer.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: metadata.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/packaging: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/platformdirs: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/pygments/styles: _mapping.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor: pyparsing
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/resolvelib: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/rich: py.typed
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor: six.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/tenacity: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor/tomli: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pip/_vendor: truststore
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pip/_vendor: webencodings
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: pip-23.2.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: pip-24.1.2.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pkg_resources: _vendor
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pkg_resources: api_tests.txt
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/pkg_resources: extern
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/pkg_resources: py.typed
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: pycairo-1.25.0.egg-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: pycairo-1.27.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: PyGObject-3.46.0.egg-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: PyGObject-3.50.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: pyproject_hooks
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: pyproject_hooks-1.1.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: requests-2.31.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: requests-2.32.3.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: _collections.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: _functools.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_distutils: _modified.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: bcppcompiler.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils/command: py37compat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils/command: register.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils/command: upload.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_distutils: compat
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: config.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: msvc9compiler.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: msvccompiler.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: py38compat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_distutils: py39compat.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_distutils: zosccompiler.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor: __init__.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: autocommand
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: autocommand-2.2.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: backports
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: backports.tarfile-1.2.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_metadata: _py39compat.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_metadata: compat
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_metadata: diagnose.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_metadata: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: importlib_metadata-8.0.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: _compat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: _legacy.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: compat
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: functional.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: future
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/importlib_resources: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: importlib_resources-6.4.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: inflect
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: inflect-7.3.1.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco: __init__.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco: collections
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco: functools
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco: functools.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: layouts.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: Lorem ipsum.txt
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: show-newlines.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: strip-prefix.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: to-dvorak.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text: to-qwerty.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: jaraco.collections-5.1.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: jaraco.context-5.3.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: jaraco.functools-4.0.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: jaraco.text-3.12.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/more_itertools: __init__.pyi
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/more_itertools: more.pyi
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/more_itertools: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/more_itertools: recipes.pyi
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: more_itertools-10.3.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor: ordered_set.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/packaging: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: packaging-24.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: platformdirs
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: platformdirs-4.2.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: ruff.toml
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor/tomli: py.typed
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: tomli-2.0.1.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: typeguard
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: typeguard-4.3.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: typing_extensions-4.12.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: wheel
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: wheel-0.43.0.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: zipp
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/_vendor: zipp.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/_vendor: zipp-3.19.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/command: bdist_wheel.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/command: register.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/command: upload.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools/command: upload_docs.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools: compat
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/config/_validate_pyproject: NOTICE
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/config: distutils.schema.json
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/config: NOTICE
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools/config: setuptools.schema.json
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools: dep_util.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools: extern
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/setuptools: modified.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/setuptools: py312compat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: setuptools-68.2.2.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: setuptools-75.1.0.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/urllib3/contrib: _securetransport
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/urllib3/contrib: emscripten
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/urllib3/contrib: securetransport.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/urllib3: http2.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: urllib3-2.0.6.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: urllib3-2.2.2.dist-info
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp: casefold.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: airmozilla.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: allstar.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: altcensored.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: amadeustv.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: art19.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: asobichannel.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: asobistage.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: atttechchannel.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: beacon.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: biqle.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: bitwave.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: boosty.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: breakcom.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: bundestag.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cableav.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: caffeinetv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: camwithher.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: carambatv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cbsinteractive.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: channel9.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: chingari.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: chirbit.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: chzzk.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cinchcast.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cliphunter.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: clipsyndicate.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cloudy.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: cloudycdn.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: daftsex.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: dangalplay.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: defense.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: digg.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: discovery.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: discoverygo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: dotsub.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: duoplay.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: echomsk.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ehow.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: einthusan.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: elementorembed.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: elevensports.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ellentube.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: eltrecetv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: engadget.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: epidemicsound.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: err.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: escapist.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: esri.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: expotv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: extremetube.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: fathom.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: filmmodu.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: flextv.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: floatplane.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: fourzerostudio.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: foxgay.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: fusion.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: gameinformer.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: gbnews.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: germanupa.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: getcourseru.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: gfycat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: giga.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: godresource.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: graspop.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: helsinki.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: hitbox.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: howcast.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: howstuffworks.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ilpost.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: jable.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: jiocinema.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: jiosaavn.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: joqrag.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: jtbc.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: kanal2.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: karrierevideos.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: keezmovies.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: kika.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: konserthusetplay.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: kukululive.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: kusi.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: laola1tv.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: laracasts.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: laxarxames.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: learningonscreen.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: linuxacademy.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: lnk.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: lnkgo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: localnews8.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: loom.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: lsm.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: m6.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: maariv.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: magentamusik.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: magentamusik360.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: malltv.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mbn.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: meta.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: metacafe.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mgoon.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: miaopai.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: microsoftvirtualacademy.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ministrygrid.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: miomio.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mnet.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: moevideo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mofosex.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mojevideo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: morningstar.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: movieclips.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mwave.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mx3.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: mychannels.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: myvi.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: newstube.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ninaprotocol.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ninenews.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: njpwworld.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: normalboots.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: nosvideo.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: nts.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: nuum.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: odatv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ooyala.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: pandoratv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: people.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: playfm.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: plays.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: playstuff.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: playvid.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: porn91.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: porncom.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: pornez.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: pornhd.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: radiobremen.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: radiocomercial.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: rbmaradio.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: recurbate.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: redge.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: regiotv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: rice.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ridehome.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: rinsefm.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: rtvnh.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: rudovideo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ruhd.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: savefrom.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: sbscokr.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: screenrec.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: seeker.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: sejmpl.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: sen.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: shared.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: sharepoint.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: snapchat.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: spankwire.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: sproutvideo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: streamcloud.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: streamff.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: swrmediathek.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: taptap.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tdslifeway.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: techtalks.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: theguardian.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: thisav.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tinypic.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tokentube.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: trilulilu.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: trtworld.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tunepk.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: turbo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tvnet.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: tvnow.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: twentyfourvideo.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: unscripted.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: veehd.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vidbit.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vidflex.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vidly.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vidyard.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vimple.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: viously.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vodlocker.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: voicerepublic.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: voot.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vrak.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vrv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vshare.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vtv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vupload.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vyborymos.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: vzaar.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: wakanim.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: wasdtv.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: watchbox.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: watchindianporn.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: willow.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: xbef.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: xfileshare.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: xiaohongshu.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: xtube.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: xuite.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: yesjapan.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: yinyuetai.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: ynet.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: yourporn.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: yourupload.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: zenporn.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/extractor: zetland.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/networking: _curlcffi.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/networking: _requests.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/networking: _websockets.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/networking: impersonate.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/networking: websocket.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages/yt_dlp/utils: progress.pyc
Only in gpodder-3.11.4-portable/data/lib/python3.11/site-packages: yt_dlp-2023.10.7.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/site-packages: yt_dlp-2024.9.27.dist-info
Only in gpodder-cd3db38-portable/data/lib/python3.11/Tools/scripts: sortperf.pyc
Only in gpodder-cd3db38-portable/data/lib/python3.11/urllib: __pycache__
Only in gpodder-3.11.4-portable/data/lib: sqlite3.43.2
Only in gpodder-cd3db38-portable/data/lib: sqlite3.46.1
Only in gpodder-3.11.4-portable/data/lib: thread2.8.7
Only in gpodder-cd3db38-portable/data/lib: thread2.8.8
Only in gpodder-3.11.4-portable/data/share/gpodder/examples: gpodder_mark_played.py
Only in gpodder-3.11.4-portable/data/share/gpodder/examples: hello_world.py
Only in gpodder-3.11.4-portable/data/share/gpodder/extensions: notification.pyc
Only in gpodder-3.11.4-portable/data/share/gpodder/extensions: notification-win32.pyc
Only in gpodder-cd3db38-portable/data/share/gpodder/extensions: podverse.py
Only in gpodder-cd3db38-portable/data/share/gpodder/extensions: podverse.pyc
Only in gpodder-cd3db38-portable/data/share/gpodder/extensions: subscription_stats.py
Only in gpodder-cd3db38-portable/data/share/gpodder/extensions: subscription_stats.pyc
Only in gpodder-cd3db38-portable/data/share/gpodder/images: directory-podverse.png
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/16x16/mimetypes: application-certificate.png
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/16x16/mimetypes: application-x-addon.png
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/16x16/mimetypes: application-x-sharedlib.png
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/16x16/mimetypes: text-x-script.png
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/16x16/places: folder-drag-accept.png
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 00008160000006810000408080010102.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 028006030e0e7ebffc7f7070c0600140.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 03b6e0fcb3499374a867c041f52298f0.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 08e8e1c95fe2fc01f976f1e063a24ccd.ani
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 1081e37283d90000800003c07f3ef6bf.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 14fef782d02440884392942c11205230.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 2870a09082c103050810ffdffffe0204.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 3085a0e285430894940527032f8b26df.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 3ecb610c1bf2410f44200f48c40d3599.ani
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 4498f0e0c1937ffe01fd06f973665830.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 5c6cd98b3f3ebcb1f9c7f1c204630408.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 6407b0e94181790501fd1e167b474872.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 640fb0e74195791501fd1ed57b41487f.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 9081237383d90e509aa00f00170e968f.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: 9d800788f1b08800ae810202380a0822.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: bd_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: bottom_left_corner.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: bottom_right_corner.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: bottom_side.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: bottom_tee.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: c7088f0f3e6c8088236ef8e1e3e70000.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: circle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: cross.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: cross_reverse.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: crossed_circle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: d9ce0ab605698f320427677b458ad60b.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: diamond_cross.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-ask.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-copy.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-link.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-move.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-no-drop.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dnd-none.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dot_box_mask.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: dotbox.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: draft_large.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: draft_small.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: draped_box.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: e29285e634086352946a0e7090d73106.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: fcf1c3c7cd4491d801f1e1c78f100000.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: fd_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: fleur.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: h_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: hand.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: hand1.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: hand2.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: icon.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: left_ptr.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: left_ptr_help.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: left_ptr_watch.ani
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: left_side.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: left_tee.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: link.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: ll_angle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: lr_angle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: pencil.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: pirate.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: plus.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: pointer-move.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: question_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: right_ptr.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: right_side.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: right_tee.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_down_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_h_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_left_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_right_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_up_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: sb_v_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: size_all.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: size_bdiag.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: size_fdiag.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: size_hor.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: size_ver.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: target.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: tcross.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: top_left_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: top_left_corner.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: top_right_corner.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: top_side.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: top_tee.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: ul_angle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: ur_angle.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: v_double_arrow.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: watch.ani
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: X_cursor.cur
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/cursors: xterm.cur
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/scalable/mimetypes: application-certificate.svg
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/scalable/places: folder-drag-accept.svg
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/scalable/status: folder-open.svg
Only in gpodder-3.11.4-portable/data/share/icons/Adwaita/symbolic/devices: input-keyboard.svg
Only in gpodder-cd3db38-portable/data/share/icons/Adwaita/symbolic/places: folder-drag-accept-symbolic.svg
Only in gpodder-cd3db38-portable/data/share/icons: AdwaitaLegacy
Only in gpodder-cd3db38-portable/data/share/locale/zh_CN/LC_MESSAGES: tre.mo
```
</p>
</details>

Even with the addition of the `AdwaitaLegacy` it is still smaller. the `Adwaita` dir is a lot smaller now. I don't know how that affects things but it seems we now have less icons?

Went from 57 dll's in `bin/*dll` to 91.

Summary (size on disk):
Files| 3.11.4| cd3db38| Difference|
|--------|--------|--------|--------|
| /share/icons| 22.5 MB| 12.8 MB| -9.7 MB
|/bin/*.dll| 53 MB | 67 MB| +14 MB|
| /share/locale| 10 MB| 11 MB| +1 MB|
| /lib/python3.11| 58 MB| 60 MB| +2 MB|
||||
| SUM| 143.5 MB| 150.8 MB| +7.3 MB|

So I think depcheck.py failure is adding about 14MB. Alwaita size decrese is helping us.

**Comment by auouymous** [comment]
Thank you so much for doing this. I was unable to fix the Windows build and was going to make a release without one.

I have opened #1662 and will try to poke at it after the release.
